---
- name: Load Virtualization Type specific vars.
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - '{{ansible_virtualization_type}}.yml'
        - main.yml
      paths:
        - 'vars'

- name: Assert that the "docker_swarm_managers" and "docker_swarm_workers" inventory groups are defined.
  fail:
    msg: "The 'docker_swarm_managers' and 'docker_swarm_workers' inventory groups are required."
  when: docker_swarm_managers is not defined or docker_swarm_workers is not defined

- include_tasks: task-present.yml
  when: docker_swarm_state == 'present'

- include_tasks: task-absent.yml
  when: docker_swarm_state == 'absent'
