---
- name: Load Virtualization Type specific vars.
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - '{{ansible_virtualization_type}}.yml'
        - main.yml
      paths:
        - 'vars'

- include_tasks: task-present.yml
  when: docker_swarm_state == 'present'

- include_tasks: task-absent.yml
  when: docker_swarm_state == 'absent'
