---
- name: Init swarm on the first node
  community.docker.docker_swarm:
    state: present
    listen_addr: "{{ docker_swarm_listen_addr }}"
    advertise_addr: "{{ docker_swarm_advertise_addr }}"
    data_path_addr: "{{ docker_swarm_data_path_addr | default(omit) }}"
    data_path_port: "{{ (docker_swarm_data_path_port | default(var_docker_swarm_data_path_port, omit)) | int }}"
  register: result
  when: inventory_hostname == groups[docker_swarm_manager_group][0]

- name: Get join-token for manager nodes
  ansible.builtin.set_fact:
    join_token_manager: "{{ hostvars[groups[docker_swarm_manager_group][0]].result.swarm_facts.JoinTokens.Manager }}"

- name: Get join-token for worker nodes
  ansible.builtin.set_fact:
    join_token_worker: "{{ hostvars[groups[docker_swarm_manager_group][0]].result.swarm_facts.JoinTokens.Worker }}"

- name: Join other managers
  community.general.docker_swarm:
    state: join
    join_token: "{{ join_token_manager }}"
    listen_addr: "{{ docker_swarm_listen_addr }}"
    advertise_addr: "{{ docker_swarm_advertise_addr }}"
    data_path_addr: "{{ docker_swarm_data_path_addr | default(omit) }}"
    data_path_port: "{{ (docker_swarm_data_path_port | default(var_docker_swarm_data_path_port, omit)) | int }}"
    remote_addrs: "{{ hostvars[groups[docker_swarm_manager_group][0]]['ansible_default_ipv4']['address'] }}:{{ docker_swarm_listen_port }}"
  when:
    - inventory_hostname in groups[docker_swarm_manager_group]
    - inventory_hostname != groups[docker_swarm_manager_group][0]

- name: Join workers
  community.docker.docker_swarm:
    state: join
    join_token: "{{ join_token_worker }}"
    listen_addr: "{{ docker_swarm_listen_addr }}"
    advertise_addr: "{{ docker_swarm_advertise_addr }}"
    data_path_addr: "{{ docker_swarm_data_path_addr | default(omit) }}"
    data_path_port: "{{ (docker_swarm_data_path_port | default(var_docker_swarm_data_path_port, omit)) | int }}"
    remote_addrs: "{{ hostvars[groups[docker_swarm_manager_group][0]]['ansible_default_ipv4']['address'] }}:{{ docker_swarm_listen_port }}"
  when:
    - inventory_hostname in groups[docker_swarm_worker_group]
